#!/bin/bash

set -euo pipefail

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:mos2dl/dotfiles.git
fi

if ! command -v vim >/dev/null; then
    sudo apt update && sudo apt install vim -y
fi

exit 0

